# Generated by Django 2.2.6 on 2019-10-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('parkingapp', '0004_parking_slot_is_reserved'),
    ]

    operations = [
        migrations.CreateModel(
            name='parking_slot_reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time_stamp', models.DateTimeField(auto_now=True)),
                ('duration_in_minutes', models.IntegerField()),
                ('booking_date', models.DateField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
                ('parking_slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parking_slot')),
            ],
        ),
        migrations.CreateModel(
            name='parking_slip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actual_entry_time', models.DateTimeField(auto_now=True)),
                ('actual_exit_time', models.DateTimeField()),
                ('basic_cost', models.IntegerField()),
                ('is_paid', models.BooleanField(default=True)),
                ('parking_slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parking_slot')),
            ],
        ),
    ]
