# Generated by Django 2.1 on 2019-11-04 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parkingapp', '__first__'),
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='parking_slip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actual_entry_time', models.DateTimeField()),
                ('actual_exit_time', models.DateTimeField()),
                ('basic_cost', models.IntegerField()),
                ('is_paid', models.BooleanField(default=True)),
                ('parking_slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parking_slot')),
            ],
        ),
        migrations.CreateModel(
            name='parking_slot_reservation',
            fields=[
                ('cost_per_hour', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time_stamp', models.DateTimeField(auto_now=True)),
                ('booking_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cost', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
                ('parking_slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parking_slot')),
            ],
        ),
    ]
