# Generated by Django 2.1 on 2019-11-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_slip',
            name='actual_entry_time',
            field=models.DateTimeField(),
        ),
    ]
