# Generated by Django 2.1 on 2019-11-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0002_auto_20191103_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_slot_reservation',
            name='cost',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
