# Generated by Django 2.2.6 on 2019-10-22 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('block_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_block_full', models.BooleanField(default=False)),
                ('no_of_floors', models.IntegerField(default=1)),
                ('block_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='floor',
            fields=[
                ('floor_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_floor_full', models.BooleanField(default=False)),
                ('is_covered', models.BooleanField(default=False)),
                ('floor_number', models.IntegerField(unique=True)),
                ('max_height', models.IntegerField()),
                ('no_of_slots', models.IntegerField(default=1)),
                ('no_of_wings', models.IntegerField(default=1)),
                ('block_code', models.CharField(max_length=30)),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.block')),
            ],
            options={
                'unique_together': {('block_id', 'floor_id')},
            },
        ),
        migrations.CreateModel(
            name='parkingLot',
            fields=[
                ('parking_lot_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_slot_available', models.BooleanField(default=True)),
                ('is_reentry_allowed', models.BooleanField(default=False)),
                ('no_of_blocks', models.IntegerField(default=1)),
                ('pincode', models.IntegerField()),
                ('is_valet_available', models.BooleanField(default=False)),
                ('landmark', models.CharField(max_length=30)),
                ('building_no', models.IntegerField()),
                ('street_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='parking_lot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkingLot'),
        ),
        migrations.CreateModel(
            name='parking_slot',
            fields=[
                ('parking_slot_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('wing_code', models.CharField(max_length=10)),
                ('slot_no', models.IntegerField(default=1)),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.floor')),
            ],
            options={
                'unique_together': {('floor_id', 'parking_slot_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('parking_lot_id', 'block_id')},
        ),
    ]
