# Generated by Django 2.2.6 on 2019-10-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='floor',
            name='floor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parking_slot',
            name='parking_slot_id',
            field=models.IntegerField(),
        ),
    ]
