# Generated by Django 2.2.6 on 2019-10-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0003_auto_20191028_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_slot',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
