# Generated by Django 2.1 on 2019-11-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sex',
        ),
        migrations.AddField(
            model_name='cost',
            name='id',
            field=models.AutoField(auto_created=True, default=5, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_numbers',
            name='vehicle_height',
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Regular_Customer'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
