# Generated by Django 2.1 on 2019-11-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191102_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='id',
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.Regular_Customer'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
